# Generated by Django 5.2.1 on 2025-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('datatime_created', models.DateTimeField(auto_now_add=True)),
                ('datatime_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(related_name='news', to='news.tag')),
            ],
        ),
    ]
